name: Dev-to-server
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Replace connection string in appsettings.json
        shell: pwsh
        run: |
          $connectionString = "${{ secrets.SWEETCRAFT_TS_CONNECTION_STRING }}"
          if ([string]::IsNullOrWhiteSpace($connectionString)) {
            Write-Host "Error: Connection string is empty!"
            exit 1
          }

          $appSettingsPath = "WebAPI/appsettings.json"
          if (Test-Path $appSettingsPath) {
            $json = Get-Content $appSettingsPath | ConvertFrom-Json
            $oldConnectionString = $json.ConnectionStrings.Default
            $json.ConnectionStrings.Default = $connectionString
            $json | ConvertTo-Json -Depth 3 | Set-Content $appSettingsPath
            Write-Host "Updated appsettings.json at: $appSettingsPath"

            if ($oldConnectionString -eq $connectionString) {
              Write-Host "No changes detected in the connection string. Skipping deployment."
              exit 0
            } else {
              Write-Host "Connection string updated. Proceeding with deployment."
            }
          } else {
            Write-Host "appsettings.json not found at $appSettingsPath!"
            exit 1
          }

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86 
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.SWEET_CRAFT_TS_WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SWEET_CRAFT_TS_SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SWEET_CRAFT_TS_SERVER_USERNAME }}
          server-password: ${{ secrets.SWEET_CRAFT_TS_SERVER_PASSWORD }}
