name: Dev-to-server
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Replace connection string in appsettings.json
        shell: pwsh
        run: |
          $connectionString = "${{ secrets.SWEET_CRAFT_TS_CONNECTION_STRING }}"
          if ([string]::IsNullOrWhiteSpace($connectionString)) {
            Write-Host "::error::Connection string is EMPTY! Check GitHub Secrets."
            exit 1
          }

          Write-Host "🔍 Connection string length: $($connectionString.Length) characters"
          
          $appSettingsPath = "WebAPI/appsettings.json"
          if (Test-Path $appSettingsPath) {
            $json = Get-Content $appSettingsPath -Raw | ConvertFrom-Json
            $json.ConnectionStrings.Default = $connectionString
            $json | ConvertTo-Json -Depth 3 | Set-Content -Encoding UTF8 $appSettingsPath

            # Проверка после изменения
            $updatedJson = Get-Content $appSettingsPath -Raw | ConvertFrom-Json
            if ([string]::IsNullOrWhiteSpace($updatedJson.ConnectionStrings.Default)) {
              Write-Host "::error::Connection string was not updated correctly!"
              exit 1
            } else {
              Write-Host "✅ Connection string successfully updated in appsettings.json"
            }
          } else {
            Write-Host "::error::appsettings.json not found at $appSettingsPath!"
            exit 1
          }

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86 
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.SWEET_CRAFT_TS_WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SWEET_CRAFT_TS_SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SWEET_CRAFT_TS_SERVER_USERNAME }}
          server-password: ${{ secrets.SWEET_CRAFT_TS_SERVER_PASSWORD }}
